# Generated by Django 3.1.2 on 2020-10-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(default='', max_length=4000)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=10)),
                ('sem', models.CharField(default='', max_length=455)),
                ('des', models.CharField(default='', max_length=90000)),
                ('passwd', models.CharField(default='', max_length=90000)),
            ],
        ),
    ]
